apiVersion: v1
kind: Service
metadata:
  name: test2-app-service
spec:
  selector:
    app: advanced-app
    component: sidecar
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP